"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Wyatt Johnston"
email = "git@wyattjohnston.email"

[ui]
default-command = "log"
diff-editor = ":builtin"

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'

[aliases]
tug = [
  "bookmark",
  "move",
  "--from",
  "closest_bookmark(@)",
  "--to",
  "closest_pushable(@)",
]
